---
- hosts: demo
  gather_facts: false
  remote_user: root
  tasks:
    - name: Building The image
      docker_image:
        name: salman8095/newimg:v1
        source: build
        build:
          path: /home/ubuntu/Project/
        state: present

    - name: Building Container
      docker_container:
        name: Salman
        image: salman8095/newimg:v1
        ports:
          - "8091:8091"
        state: started
