apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking
  labels:
    app: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: B01
        image: salman8095/banking:v1
        ports:
        - containerPort: 8091

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: bank
  ports:
    - port: 8091
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8091
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31000
